import Foundation
import CoreGraphics

// MARK: - Dependency Graph

public enum GraphNodeKind: String, Codable, Sendable, CaseIterable {
    case volume
    case application
    case directory
    case package
    case cache
    case file
    case orphan

    public var displayName: String {
        switch self {
        case .volume: return "Volume"
        case .application: return "Application"
        case .directory: return "Directory"
        case .package: return "Package"
        case .cache: return "Cache"
        case .file: return "File"
        case .orphan: return "Orphan"
        }
    }

    public var systemImage: String {
        switch self {
        case .volume: return "externaldrive.fill"
        case .application: return "app.fill"
        case .directory: return "folder.fill"
        case .package: return "shippingbox.fill"
        case .cache: return "bolt.horizontal.circle.fill"
        case .file: return "doc.fill"
        case .orphan: return "exclamationmark.triangle.fill"
        }
    }
}

public enum GraphEdgeKind: String, Codable, Sendable, CaseIterable {
    case owns
    case dependsOn
    case generatedBy
    case sharedWith
    case installedBy

    public var displayName: String {
        switch self {
        case .owns: return "owns"
        case .dependsOn: return "depends on"
        case .generatedBy: return "generated by"
        case .sharedWith: return "shared with"
        case .installedBy: return "installed by"
        }
    }
}

public struct GraphNode: Identifiable, Codable, Sendable, Equatable {
    public var id: String
    public var label: String
    public var kind: GraphNodeKind
    public var path: String?
    public var bytes: Int64
    public var category: StorageCategory?

    public init(
        id: String,
        label: String,
        kind: GraphNodeKind,
        path: String? = nil,
        bytes: Int64 = 0,
        category: StorageCategory? = nil
    ) {
        self.id = id
        self.label = label
        self.kind = kind
        self.path = path
        self.bytes = bytes
        self.category = category
    }
}

public struct GraphEdge: Identifiable, Codable, Sendable, Equatable {
    public var id: String { "\(sourceID)->\(targetID):\(kind.rawValue)" }
    public var sourceID: String
    public var targetID: String
    public var kind: GraphEdgeKind

    public init(sourceID: String, targetID: String, kind: GraphEdgeKind) {
        self.sourceID = sourceID
        self.targetID = targetID
        self.kind = kind
    }
}

public struct DependencyGraph: Codable, Sendable, Equatable {
    public var nodes: [GraphNode]
    public var edges: [GraphEdge]

    public init(nodes: [GraphNode] = [], edges: [GraphEdge] = []) {
        self.nodes = nodes
        self.edges = edges
    }
}

// MARK: - Duplicates

public struct DuplicateGroup: Identifiable, Codable, Sendable, Equatable, Hashable {
    public var id: String { contentHash }
    public var contentHash: String
    public var totalBytes: Int64
    public var wastedBytes: Int64
    public var paths: [String]
    public var fileName: String
    public var matchKind: DuplicateMatchKind

    public init(
        contentHash: String,
        totalBytes: Int64,
        wastedBytes: Int64,
        paths: [String],
        fileName: String,
        matchKind: DuplicateMatchKind = .contentHash
    ) {
        self.contentHash = contentHash
        self.totalBytes = totalBytes
        self.wastedBytes = wastedBytes
        self.paths = paths
        self.fileName = fileName
        self.matchKind = matchKind
    }
}

public enum DuplicateMatchKind: String, Codable, Sendable {
    case contentHash
    case fileName
    case sizeAndName
}

// MARK: - Application orphans

public struct InstalledApplication: Identifiable, Codable, Sendable, Equatable {
    public var id: String { bundleID ?? path }
    public var name: String
    public var path: String
    public var bundleID: String?
    public var supportPaths: [String]
    public var totalSupportBytes: Int64

    public init(
        name: String,
        path: String,
        bundleID: String? = nil,
        supportPaths: [String] = [],
        totalSupportBytes: Int64 = 0
    ) {
        self.name = name
        self.path = path
        self.bundleID = bundleID
        self.supportPaths = supportPaths
        self.totalSupportBytes = totalSupportBytes
    }
}

public struct OrphanArtifact: Identifiable, Codable, Sendable, Equatable {
    public var id: String { path }
    public var path: String
    public var name: String
    public var bytes: Int64
    public var kind: OrphanKind
    public var suspectedOwner: String?
    public var confidence: Double
    public var reason: String

    public init(
        path: String,
        name: String,
        bytes: Int64,
        kind: OrphanKind,
        suspectedOwner: String? = nil,
        confidence: Double,
        reason: String
    ) {
        self.path = path
        self.name = name
        self.bytes = bytes
        self.kind = kind
        self.suspectedOwner = suspectedOwner
        self.confidence = confidence
        self.reason = reason
    }
}

public enum OrphanKind: String, Codable, Sendable, CaseIterable {
    case supportData
    case preferences
    case caches
    case containers
    case plugins
    case logs
    case leftover

    public var displayName: String {
        switch self {
        case .supportData: return "Application Support"
        case .preferences: return "Preferences"
        case .caches: return "Caches"
        case .containers: return "Containers"
        case .plugins: return "Plugins"
        case .logs: return "Logs"
        case .leftover: return "Leftover"
        }
    }

    public var systemImage: String {
        switch self {
        case .supportData: return "internaldrive"
        case .preferences: return "gearshape"
        case .caches: return "bolt.circle"
        case .containers: return "shippingbox"
        case .plugins: return "puzzlepiece.extension"
        case .logs: return "doc.text"
        case .leftover: return "trash"
        }
    }
}

public struct OrphanReport: Codable, Sendable, Equatable {
    public var applications: [InstalledApplication]
    public var orphans: [OrphanArtifact]
    public var totalOrphanBytes: Int64

    public init(
        applications: [InstalledApplication] = [],
        orphans: [OrphanArtifact] = [],
        totalOrphanBytes: Int64 = 0
    ) {
        self.applications = applications
        self.orphans = orphans
        self.totalOrphanBytes = totalOrphanBytes
    }
}

// MARK: - History / trends

public struct ScanSnapshot: Identifiable, Codable, Sendable, Equatable {
    public var id: UUID
    public var startedAt: Date
    public var finishedAt: Date?
    public var status: ScanStatus
    public var filesScanned: Int
    public var bytesScanned: Int64
    public var categoryTotals: [String: Int64]

    public init(
        id: UUID,
        startedAt: Date,
        finishedAt: Date?,
        status: ScanStatus,
        filesScanned: Int,
        bytesScanned: Int64,
        categoryTotals: [String: Int64] = [:]
    ) {
        self.id = id
        self.startedAt = startedAt
        self.finishedAt = finishedAt
        self.status = status
        self.filesScanned = filesScanned
        self.bytesScanned = bytesScanned
        self.categoryTotals = categoryTotals
    }
}

public struct TrendPoint: Identifiable, Codable, Sendable, Equatable {
    public var id: UUID { sessionID }
    public var sessionID: UUID
    public var date: Date
    public var totalBytes: Int64
    public var fileCount: Int

    public init(sessionID: UUID, date: Date, totalBytes: Int64, fileCount: Int) {
        self.sessionID = sessionID
        self.date = date
        self.totalBytes = totalBytes
        self.fileCount = fileCount
    }
}

public struct CategoryDelta: Identifiable, Codable, Sendable, Equatable {
    public var id: String { category.rawValue }
    public var category: StorageCategory
    public var previousBytes: Int64
    public var currentBytes: Int64

    public var deltaBytes: Int64 { currentBytes - previousBytes }

    public init(category: StorageCategory, previousBytes: Int64, currentBytes: Int64) {
        self.category = category
        self.previousBytes = previousBytes
        self.currentBytes = currentBytes
    }
}

public struct HistoryReport: Codable, Sendable, Equatable {
    public var snapshots: [ScanSnapshot]
    public var trend: [TrendPoint]
    public var categoryDeltas: [CategoryDelta]
    public var largestGrowth: [CategoryDelta]
    public var largestShrink: [CategoryDelta]

    public init(
        snapshots: [ScanSnapshot] = [],
        trend: [TrendPoint] = [],
        categoryDeltas: [CategoryDelta] = [],
        largestGrowth: [CategoryDelta] = [],
        largestShrink: [CategoryDelta] = []
    ) {
        self.snapshots = snapshots
        self.trend = trend
        self.categoryDeltas = categoryDeltas
        self.largestGrowth = largestGrowth
        self.largestShrink = largestShrink
    }
}
